
modLoader="javafml"
loaderVersion="[39,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/Stereowalker/Controller-Support-Mod/issues"
logoFile="pack.png"
[[mods]]
modId="controllermod"
version="${file.jarVersion}"
displayName="Controller Support"
updateJSONURL="https://raw.githubusercontent.com/Stereowalker/Controller-Support-Mod/master/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/controller-mod"
credits="I'd like to thank all my supporters on Patreon for giving me a reason to continue modding, and you for downloading and playing with this mod"
authors="Stereowalker"
description='''
Grants the ablility to play Minecraft with controllers and gives opportunity to those who want to play split-screen.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.controllermod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[39,)" #mandatory
    ordering="NONE"
    side="CLIENT"
# Here's another dependency
[[dependencies.controllermod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.controllermod]]
    modId="unionlib"
    mandatory=true
    versionRange="[6.1,6.2)"
    ordering="NONE"
    side="BOTH"